"use client";
import Footer from "./components/footer/footer";
import { AuthContextProvider } from "./context/AuthContext";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          {children}
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
